import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import Head from "next/head";
import { AppSidebar } from "./components/app-sidebar";
import MobileAppBar from "./components/MobileAppBar";
import MobileFooter from "./components/MobileFooter";
import AuthModal from "./components/AuthModal";
import VerificationModal from "./components/VerificationModal";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className="" lang="en">
       <Head>
        {/* Android Chrome status bar */}
        <meta name="theme-color" content="#0f172a" />
        
        {/* iOS Safari status bar */}
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
      </Head>

      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900`}>
        <SidebarProvider>
          <div className="flex h-full w-full">
            <AppSidebar />

            <main className="flex-1">
   
                <MobileAppBar />
                  
                  {children}
                   <AuthModal />
                  <VerificationModal/>
                  <MobileFooter />
          
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
