import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "./components/app-sidebar";
import MobileAppBar from "./components/MobileAppBar";
import MobileFooter from "./components/MobileFooter";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className="" lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-900`}>
        <SidebarProvider>
          <div className="flex h-full w-full">
            <AppSidebar />

            <main className="flex-1">
   
                <MobileAppBar />
                  
                  {children}
                  <MobileFooter />
          
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
